### ISSUE TITLE
It is not working, i followed up instructions.

### ISSUE THREAD

**Issue by rodvan** [TheNamesRay/Habbo-in-HTML5#1]
It is displaying 
[22:20:28] Ң5 Һ@ɮƁ۝ ϞɘɌטɘȐ - ȻЯËɅŦҼԁ ɮӋ ӃҼԀ༏ ΛɢɃѺɢɌË
[22:20:28] Server now listening on port 7858
And I enter:
localhost:7858 and nothing goes on.
Page wont load, already imported SQL and everything.
Would appreciate response.

**Comment by TheNamesRay** [comment]
I cannot reproduce the issue you are having. I just set it up and it is working.
You need to edit index.php and change my IP to yours (or localhost).
That is most likely the issue here.
